# Generated by Django 5.0.3 on 2024-04-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
